# Generated by Django 2.2.4 on 2019-08-27 09:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 19', regex='^.{19}$')])),
                ('amount', models.IntegerField()),
                ('location', models.TextField()),
                ('acc_num', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('date_of_transaction', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
