# Generated by Django 2.2.4 on 2019-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlaks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
