# Generated by Django 2.2.4 on 2019-08-28 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlaks_app', '0003_atm_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='month',
        ),
        migrations.AlterField(
            model_name='atm',
            name='acc_num',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')]),
        ),
        migrations.AlterField(
            model_name='atm',
            name='pan_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 19', regex='^.{19}$')]),
        ),
    ]
