# Generated by Django 2.2.4 on 2019-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlaks_app', '0007_auto_20190904_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Reversed', 'Reversed')], default='Success', max_length=8),
        ),
    ]
